# NumPy

Creating Arrays:
- 1D Array, 2D Array, Array of Zeros, Array of Ones, Array with Range, Identity, Array with Step Size
- dimention, shape, size, type

Basic Array Operations:
- Element-wise Addition, Element-wise Addition with another Array, Element-wise Multiplication, Element-wise Subtraction, Element-wise Division, Dot Product, Reshape Array

Mathematical Functions:
- Sine of each element, Cosine of each element, Tangent of each element, Exponentiation, Natural Log (log base e), Logarithm base 10

Statistical Functions:
- Mean, Median, Standard Deviation, Sum, Minimum and Maximum

Random Numbers:
- Random Array (values between 0 and 1), Random Integer Array (range 0 to 10)

Matrix Operations:
- Matrix Multiplication (Dot product), Transpose of a Matrix, determinant (using linalg), inverse, eigen, solve

### Q. Solving linear equation
```
x+y+z=6
2x+2y+3z=14
3x+4y+z=10
```

In [1]:
print("Hello, world")

Hello, world


In [2]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 56.9 kB/s  0:03:12m0:00:0300:12

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
# Making arrays with numpy

# 1d array

arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [5]:
arr2 = np.array([[2, 4], [4, 5]])
print(arr2)

[[2 4]
 [4 5]]


In [7]:
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

2
4
int64


In [ ]:
# array with zeros

zeros = np.zeros((3, 4), int)
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [14]:
zeros.dtype

dtype('int64')

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [41]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
# making 4x4 matrix

np.array(([1, 2, 3, 4],[5, 6, 7, 8],[3, 4, 5, 6],[1, 3, 4, 5]))


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 4, 5, 6],
       [1, 3, 4, 5]])

In [ ]:
np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 3, 4, 5, 6]).reshape(4, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 6],
       [5, 4, 3, 2],
       [3, 4, 5, 6]])

In [29]:
arr2

array([[2, 4],
       [4, 5]])

In [31]:
arr2.flatten()

array([2, 4, 4, 5])

In [37]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2

array([[2, 4],
       [4, 5]])

In [ ]:
# add with integer

arr2 + 5

array([[ 7,  9],
       [ 9, 10]])

In [42]:
np.array((1, 2, 3))

array([1, 2, 3])

In [43]:
arr1 = np.arange(4).reshape(2, 2)

In [ ]:
# addition of two matrix (element wise)

arr1 + arr2

array([[2, 5],
       [6, 8]])

In [45]:
arr1 / arr2

array([[0.  , 0.25],
       [0.5 , 0.6 ]])

In [48]:
# using random numbers

np.random.rand(2, 2)

array([[0.99489438, 0.13713568],
       [0.33818862, 0.87706578]])

In [52]:
arr = np.random.randint(1, 10, (3, 3))
arr

array([[4, 8, 1],
       [2, 3, 4],
       [6, 1, 7]])

In [57]:
# mathematical operations

np.sin(arr)

array([[-0.7568025 ,  0.98935825,  0.84147098],
       [ 0.90929743,  0.14112001, -0.7568025 ],
       [-0.2794155 ,  0.84147098,  0.6569866 ]])

In [54]:
np.cos(arr)

array([[-0.65364362, -0.14550003,  0.54030231],
       [-0.41614684, -0.9899925 , -0.65364362],
       [ 0.96017029,  0.54030231,  0.75390225]])

In [55]:
np.exp(arr)

array([[5.45981500e+01, 2.98095799e+03, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [4.03428793e+02, 2.71828183e+00, 1.09663316e+03]])

In [56]:
np.log(arr)

array([[1.38629436, 2.07944154, 0.        ],
       [0.69314718, 1.09861229, 1.38629436],
       [1.79175947, 0.        , 1.94591015]])

In [65]:
# Statistical Functions

arr = np.array((5, 2, 8, 4, 3, 1, 12, 32, 43, 3, 2, 1)).reshape(4, 3)
arr

array([[ 5,  2,  8],
       [ 4,  3,  1],
       [12, 32, 43],
       [ 3,  2,  1]])

In [72]:
print(f"Minimum = {arr.min()}")
print(f"Maximum = {arr.max()}")
print(f"Mean = {arr.mean()}")
print(f"Median = {np.median(arr)}")
print(f"S.D = {arr.std()}")

Minimum = 1
Maximum = 43
Mean = 9.666666666666666
Median = 3.5
S.D = 13.00213657656139


In [74]:
# Matrix operations

mat1 = np.array((1, 3, 5, 7)).reshape(2, 2)
mat2 = np.array((2, 4, 6, 8)).reshape(2, 2)

print("Matrix 1: \n", mat1)
print("Matrix 2: \n", mat2)

Matrix 1: 
 [[1 3]
 [5 7]]
Matrix 2: 
 [[2 4]
 [6 8]]


In [75]:
# dot product

np.dot(mat1, mat2)

array([[20, 28],
       [52, 76]])

In [ ]:
vect1 = np.array((1, 2))
vect2 = np.array((3, 4))

np.dot(vect1, vect2)

np.int64(11)

In [ ]:
# matrix multiplication

np.matmul(mat1, mat2)

array([[20, 28],
       [52, 76]])

In [82]:
# element wise multiply

mat1 * mat2

array([[ 2, 12],
       [30, 56]])

In [86]:
# Matrix transpose

print("Matrix")
print(mat1)
print("Its transpose")
print(mat1.T)

Matrix
[[1 3]
 [5 7]]
Its transpose
[[1 5]
 [3 7]]


In [88]:
# Inverse

print(mat1)
print("Its inverse")
print(np.linalg.inv(mat1))

[[1 3]
 [5 7]]
Its inverse
[[-0.875  0.375]
 [ 0.625 -0.125]]


In [89]:
# Determinant

print(mat1)
print("Its determinant")
print(np.linalg.det(mat1))

[[1 3]
 [5 7]]
Its determinant
-7.999999999999998


In [92]:
# Eigen values and eigen vectors

print(mat1)
print("Its eigenvalues and eigenvectors")
eigenvalues, eigenvectors = np.linalg.eig(mat1)
print(eigenvalues)
print(eigenvectors)

# print(np.linalg.eig(mat2))

[[1 3]
 [5 7]]
Its eigenvalues and eigenvectors
[-0.89897949  8.89897949]
[[-0.84494897 -0.35505103]
 [ 0.53484692 -0.93484692]]


### Q. Solving linear equation
```
x+y+z=6
2x+2y+3z=14
3x+4y+z=10
```

In [96]:
A = np.array(((1, 1, 1), (2, 2, 3), (3, 4, 1)))
B = np.array((6, 14, 10))

X = np.linalg.solve(A, B)

print("A\n", A)
print("B\n", B)
print("X\n", X)

A
 [[1 1 1]
 [2 2 3]
 [3 4 1]]
B
 [ 6 14 10]
X
 [ 8. -4.  2.]


In [97]:
A > 3

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [ ]:
s = 5/3

print(f"{7/3:.2f}")

2.33
